In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
from ipywidgets.embed import embed_minimal_html

# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head(5)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Chuy,-33.6971,-53.4616,41.83,81,23,5.26,UY,2022-07-13 00:23:46
1,1,Qaanaaq,77.4840,-69.3632,41.23,75,87,5.08,GL,2022-07-13 00:23:47
2,2,Nyurba,63.2842,118.3319,66.61,82,66,4.68,RU,2022-07-13 00:23:47
3,3,Barra Patuca,15.8000,-84.2833,79.50,88,100,9.69,HN,2022-07-13 00:23:47
4,4,Lasa,46.6166,10.7002,63.48,68,71,4.03,IT,2022-07-13 00:23:48

In [10]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [11]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [12]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
## Adjust Zoom
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
#Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
#Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [24]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(5)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
3,3,Barra Patuca,15.8000,-84.2833,79.50,88,100,9.69,HN,2022-07-13 00:23:47
5,5,Marzuq,14.4000,46.4667,77.76,40,100,3.71,YE,2022-07-13 00:23:48
9,9,Hilo,19.7297,-155.0900,87.28,76,75,10.36,US,2022-07-13 00:20:52
10,10,Thompson,55.7435,-97.8558,75.36,35,20,3.44,CA,2022-07-13 00:23:49
12,12,Atuona,-9.8000,-139.0333,77.76,77,27,19.08,PF,2022-07-13 00:23:50

In [25]:
preferred_cities_df.count()

City_ID       212
City          212
Lat           212
Lng           212
Max Temp      212
Humidity      212
Cloudiness    212
Wind Speed    212
Country       212
Date          212
dtype: int64

In [26]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(5)

            City Country  Max Temp      Lat       Lng Hotel Name
3   Barra Patuca      HN     79.50  15.8000  -84.2833
5         Marzuq      YE     77.76  14.4000   46.4667
9           Hilo      US     87.28  19.7297 -155.0900
10      Thompson      CA     75.36  55.7435  -97.8558
12        Atuona      PF     77.76  -9.8000 -139.0333

In [46]:
import traceback

In [33]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [47]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print("This is kind of working")
    except (IndexError):
        print("Hotel not found... IndexError")
    except (KeyError):
        print("Hotel not found... KeyError")

Hotel not found... IndexError
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
Hotel not found... IndexError
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
Hotel not found... IndexError
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working
This is kind of working

In [44]:
hotel_df.head(20)

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Barra Patuca,HN,79.50,15.8000,-84.2833,
5,Marzuq,YE,77.76,14.4000,46.4667,
9,Hilo,US,87.28,19.7297,-155.0900,Hilo Hawaiian Hotel
10,Thompson,CA,75.36,55.7435,-97.8558,Burntwood Hotel
12,Atuona,PF,77.76,-9.8000,-139.0333,Villa Enata
13,Bathsheba,BB,83.01,13.2167,-59.5167,Atlantis Hotel
15,Butaritari,KI,82.40,3.0707,172.7902,Isles Sunset Lodge
17,Kavaratti,IN,81.09,10.5669,72.6420,Green leaf
18,Alofi,NU,80.49,-19.0595,-169.9187,Taloa Heights
22,Merauke,ID,77.95,-8.4667,140.3333,
23,Georgetown,MY,76.95,5.4112,100.3354,Cititel Penang
24,Weyburn,CA,79.02,49.6668,-103.8511,Perfect Inns & Suites
27,Corn Island,NI,81.01,12.1694,-83.0418,Big Fish Guest House
28,Bhadasar,IN,85.87,28.2833,74.3167,OMPRAKASH JAKHAR
30,Albany,US,78.89,42.6001,-73.9662,
32,Faanui,PF,78.87,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
47,Lorengau,PG,84.51,-2.0226,147.2712,Lorengau Harbourside Hotel
51,Lahad Datu,MY,79.07,5.0268,118.3270,The 27th House
55,Vaini,TO,80.76,-21.2000,-175.2000,Keleti Beach Resort
56,Kapaa,US,84.52,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort

In [48]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [49]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

Here's what these tags mean:

The "dl" tag is a description list (dl).

The "dt" tag is a term or name in a description list that is nested under the "dl" tag.

The "dd" tag is used to define the term or name or "<dt>" tag.
    
    
If we were to write out these tags on paper, it would look like this.

- Description List: "dl"
    - Description Term: "dt"
        - Description Definition: "dd"
    - Description Term: "dt"
        - Description Definition: "dd"

In [50]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""

In [51]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [52]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [53]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))